DROP TABLE artifact_graph;
DROP TABLE artifact;
DROP TABLE artifact_edge;
DROP TABLE artifact_producer_edge;
DROP TABLE artifact_dtype_edge;
DROP TABLE version;
DROP TABLE version_parent;
DROP TABLE version_relation;
DROP TABLE hunk;
