[package]
name = "heraclitus"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Andrew Champion <andrew.champion@gmail.com>"]
description = "A system for managing versioned, dependent data artifacts."
readme = "README.md"

[lib]
name = "heraclitus"
path = "src/lib.rs"

[[bin]]
name = "hera"
path = "src/bin.rs"

[dependencies]
daggy = "*"
enum-set = "*"
failure = "0.1"
lazy_static = "*"
maplit = "*"
petgraph = { version = "*", features = ["serde-1"] }
postgres = { version = "0.15", features = ["with-uuid"] }
postgres_array = "0.9"
postgres-derive = "0.3"
schemer = "0.1.2"
schemer-postgres = "0.1.1"
serde = "*"
serde_derive = "*"
serde_json = "*"
url = "*"
uuid = { version = "0.5", features = ["use_std", "v4", "v5"] }

[patch.crates-io]
schemer = { path = "../schemer/schemer" }
